### ISSUE TITLE
button von Box Kontakt wird verschoben (responsive)

### ISSUE THREAD

**Issue by NMH1988** [PraxisGyn/gawriljuk.de#5]
![image](https://user-images.githubusercontent.com/19816710/31384454-5b2f6096-adbf-11e7-8084-ee69298796be.png)

Haben Sie vielleicht Idee um dieses Problem zu lösen

**Comment by gallien** [comment]
Das kann ich nich nachvollziehen. Das ist auch nicht der letzte Stand.
